name: Pull Request Lint

on:
  pull_request:
    # By default, a workflow only runs when a pull_request's activity type is opened, synchronize, or reopened. We
    # explicity override here so that PR titles are re-linted when the PR text content is edited.
    #
    # Possible values: https://help.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-event-pull_request
    types: [opened, edited, reopened]

jobs:
  pr-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: morrisoncole/pr-lint-action@v1.5.0
        with:
          title-regex: "\\[(CU-.+|[nN][oO][cC][aA][rR][dD]|[wW][iI][pP])\\] .+"
          on-failed-regex-fail-action: false
          on-failed-regex-request-changes: true
          on-failed-regex-create-review: true
          on-failed-regex-comment:
            "Pull request title doesn't conform regex: `%regex%`! <br /> More info on this: https://collab.namecheap.net/display/CT/Working+together"
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
